/*****************

SQL for the creation of the tables for the netquery app
Jesse Fagan
July 15, 2013

******************/

/** responses

the responses for each survey exist in a single table

I am concerned about the number of columns that may be created. So table is very tall instead of wide. 

The response is stored in a long text field. The text field is intended to store JSON data so that the response can store any number of different response types. I'm not sure if this is the best option, but it's what I'm going with right now. It should make things versatile.

I want to explore the possibility of CouchDB instead, since it seems like it adheres to this sort of model.

**/

create database if not exists netquery;

use netquery;

/** 
response contains a JSON text object of the response
logic contains a JSON text object of the logic 
	(at the time the survey was conducted)
	(this means we can change the survey logic on the fly, add questions, remove questions.. etc)
	(Getting the data out into a tabular format... well, we'll get to that)
**/


create table if not exists responses 
(
	id varchar(40) not null primary key, -- this will be a GUID generated by the app
	rid varchar(40), -- the respondent id
	sid varchar(40), -- the survey id
	qid varchar(40), -- the question id
	lastupdated datetime, -- the last time the record was changed --the response details
	response longtext,
	logic longtext
);

create table if not exists respondents
(
	id varchar(40) not null primary key, -- this will be a GUID generated by the app
	datecreated datetime,
	ipaddress varchar(40),
	survey varchar(40),
	surveystatus varchar(40),
	surveylogic longtext,
	grouplogic longtext,
	lastgroup int,
	username varchar(40)
);

create table if not exists namelist
(
	id varchar(40) not null primary key, 
	rid varchar(40),
	sid varchar(40),
	name varchar(40),
	namelist longtext,
	details longtext
);

create table if not exists users
(
	username varchar(40) not null primary key,
	fname varchar(40),
	lname varchar(40),
	email varchar(254),
	pwd varchar(40)
);

create table if not exists errortracking
(
	errid int not null auto_increment primary key,
	rid varchar(40),
	errdate datetime,
	error longtext,
	stack longtext,
	appstate longtext
);



-- RKzYyWb9b7SQncpE









